apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policygen-user-workload-monitoring
policyDefaults:
  categories:
    - CM Configuration Management
  controls: 
    - CM-1 Baseline Configuration
  namespace: policy-acm
  remediationAction: enforce
  severity: medium
policies:
- name: policy-user-workload-monitoring
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: ../manifest
  placement:
    clusterSelectors:
      env: "multicloud"