apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: User-workload-monitoring
policyDefaults:
  categories:
    - CM Configuration Management
  controls: 
    - CM-1 Baseline Configuration
  namespace: policies
  remediationAction: enforce
  severity: medium
  placement:
    name: demo-placement-rule
    labelSelector:
      name: all
policies:
- name: policy-user-workload-monitoring 
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: ./common