apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: application/overlays/quick-start-app
    apps.open-cluster-management.io/reconcile-option: replace
  name: sub-root
  namespace: ns-root
spec:
  channel: ns-channel/ch-rhacm
  placement:
    placementRef:
      kind: PlacementRule
      name: pl-root