apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: quick-start-app
  name: pl-quick-start-app
  namespace: quick-start-test
spec:
  clusterSelector:
    matchLabels:
      env : 'multicloud'