apiVersion: v1
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: "observabilityacm"
      endpoint: "s3.us-east-1.amazonaws.com"
      insecure: true
      access_key: ""
      secret_key: ""
kind: Secret
metadata:
  name: thanos-object-storage
  namespace: open-cluster-management-observability
type: Opaque