apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: tekton/overlays/classic
    apps.open-cluster-management.io/reconcile-option: replace
  labels:
    app: demo-tekton-build-env
    apps.open-cluster-management.io/reconcile-rate: high
  name: demo-tekton-build-env-subscription
  namespace: demo-tekton-build-env
spec:
  channel: ns-channel/ch-quick-start-app
  placement:
    placementRef:
      kind: PlacementRule
      name: demo-tekton-build-env-placement
  secondaryChannel: ''