apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  annotations: {}
  labels:
    app: demo-tekton-build-env
  name: demo-tekton-build-env-placement
  namespace: demo-tekton-build-env
spec:
  clusterSelector:
    matchLabels:
      local-cluster: 'true'