apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: high
  name: ch-quick-start-app
  namespace: ns-channel-quick-start-app
  labels:
    app: quick-start-app
spec:
  type: Git
  pathname: 'https://github.com/mcombi/my-quarkus-quick-start-config.git'