apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: app/overlays
    apps.open-cluster-management.io/reconcile-option: replace
  name: sub-root
  namespace: quick-start-test
spec:
  channel: ns-channel/ch-rhacm
  placement:
    placementRef:
      kind: PlacementRule
      name: pl-root