apiVersion: v1
kind: Namespace
metadata:
  name: policy-acm
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: policy-user-workload-monitoring
  namespace: policy-acm
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - policy-generator-example
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: 
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: policy-user-workload-monitoring
  name: policy-user-workload-monitoring-subscription
  namespace: policy-acm
spec:
  allow:
    - apiVersion: policy.open-cluster-management.io/v1
      kinds:
        - "*"
    - apiVersion: apps.open-cluster-management.io/v1
      kinds:
        - PlacementRule
  channel: ns-channel/ch-rhacm
  placement:
    placementRef:
      kind: PlacementRule
      name: user-workload-monitoring-placement
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: policy-user-workload-monitoring
  name: user-workload-monitoring-placement
  namespace: policy-acm
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: local-cluster
        operator: In
        values:
          - "true"