apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: config-data-policies
policyDefaults:
  categories:
    - CM Configuration Management
  controls: 
    - CM-1 Baseline Configuration
  namespace: policies
  remediationAction: inform
  severity: medium
  placement:
    name: policy-uwm-placement
    labelSelector:
      name: all
policies:
- name: policy-user-workload-monitoring
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: ./base/manifest