apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: quick-start-app
  namespace: ns-quick-start-app
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - quick-start-app